### ISSUE TITLE
Errored 

### ISSUE THREAD

**Issue by EverydayPancake** [Traphiccone/MM2-Buddy#45]
![2024-05-05_13h34_23](https://github.com/Traphiccone/MM2-Buddy/assets/149656926/693ac625-b720-4f2b-b7c8-5f350564efba)

I cant use MM2-Buddy now

Thank you for your assistance,

**Comment by Traphiccone** [comment]
Does this happen immediately upon launching MM2-Buddy?  or after hitting Start?

**Comment by Traphiccone** [comment]
> ![2024-05-05_13h34_23](https://private-user-images.githubusercontent.com/149656926/327989601-693ac625-b720-4f2b-b7c8-5f350564efba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMTY2ODAsIm5iZiI6MTcxNTAxNjM4MCwicGF0aCI6Ii8xNDk2NTY5MjYvMzI3OTg5NjAxLTY5M2FjNjI1LWI3MjAtNGYyYi1iN2M4LTVmMzUwNTY0ZWZiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQxNzI2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTQzZGExYjY3NzI1YmRiZjliODkwNjhkYTRkMGJkOTI3ZmJkODBlNjc1YzQ1ZTBkOGM2ZWI2MDU1NTJlNWE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OV9VrkshZuweKkLrCRb0xt0LdF0NznHu_dEJpUbiEHc)
> 
> I cant use MM2-Buddy now
> 
> Thank you for your assistance,

Does this happen immediately upon launching MM2-Buddy? or after hitting Start?

**Comment by EverydayPancake** [comment]
>

 > I cant use MM2-Buddy now
> > Thank you for your assistance,
> 
> Does this happen immediately upon launching MM2-Buddy? or after hitting Start?

Yes, this happen immediately upon launching MM2-Buddy. double click 
like this 

![2024-05-07_14h12_12](https://github.com/Traphiccone/MM2-Buddy/assets/149656926/bfe29ec6-18c1-4244-ab96-2f75a9620dce)

**Comment by Traphiccone** [comment]
Sorry for the delay.  If you're still having problems, can you go into your appdata folder on your PC and upload all the files in the appdata MM2Buddy folder? 
It should be something like C:\Users\username\AppData\Roaming\MM2Buddy

There should be three files: crashreport.txt, MM2BuddySettings.config, and MM2DataLog.txt.  Just copy paste all those here in a comment.  Also are you using the Excel logging feature?  If you are, it may help to upload that as well.

**After** you upload those, a quick fix might be to cut(not copy) and paste those someplace else/safe like your desktop, and rerun MM2Buddy, which will force the program to generate new appdata files.  Same with the Excel log if you're using that feature.

Let me know how it goes,
![image](https://github.com/Traphiccone/MM2-Buddy/assets/48689014/3b15f034-9be9-4b66-9afa-203c1fae1439)

**Comment by EverydayPancake** [comment]
Hello Traphiccone Thank you for replies :)
 
**MM2DataLog**
![2024-05-14_19h21_19](https://github.com/Traphiccone/MM2-Buddy/assets/149656926/25db1678-5328-4937-9041-2b71bf8ec605)

**MM2BuddySettings.config**
![2024-05-14_19h22_29](https://github.com/Traphiccone/MM2-Buddy/assets/149656926/9a4f8019-d732-48f7-acb7-5ed287d83118)

**crashreport.txt**
2024/05/14 18:57:16: System.ArgumentException: Object of type 'System.String' cannot be converted to type 'System.Int32'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(StackAllocedArguments& stackArgs, ReadOnlySpan`1 parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeOneParameter(Object obj, BindingFlags invokeAttr, Binder binder, Object parameter, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at MM2Buddy.MainWindow.ReadAllSettings() in R:\Tyler\Desktop\MarioMaker2 Logger\WPFMM2Buddy\MM2Buddy\MainWindow.xaml.cs:line 272
   at MM2Buddy.MainWindow.MainWindow_Loaded(Object sender, RoutedEventArgs e) in R:\Tyler\Desktop\MarioMaker2 Logger\WPFMM2Buddy\MM2Buddy\MainWindow.xaml.cs:line 321
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

**Comment by EverydayPancake** [comment]
It works again Thank you!
Three files: 
crashreport.txt,
MM2BuddySettings.config,
MM2DataLog.txt.

I remove those three files (your advised) and restart! Thank you!
